# Generated by Django 4.1.5 on 2023-01-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Login users', 'verbose_name_plural': 'Login users'},
        ),
    ]
