# Generated by Django 4.1.5 on 2023-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RezervModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_service', models.BooleanField(blank=True, default=False, null=True)),
                ('Interim_service', models.BooleanField(blank=True, default=False, null=True)),
                ('Add_a_mot', models.BooleanField(blank=True, default=False, null=True)),
                ('Wheelaligment', models.BooleanField(blank=True, default=False, null=True)),
                ('Diagnose', models.BooleanField(blank=True, default=False, null=True)),
                ('Tyres', models.BooleanField(blank=True, default=False, null=True)),
                ('Clutches', models.BooleanField(blank=True, default=False, null=True)),
                ('Suspension', models.BooleanField(blank=True, default=False, null=True)),
                ('Cambelt', models.BooleanField(blank=True, default=False, null=True)),
                ('Exhaust', models.BooleanField(blank=True, default=False, null=True)),
                ('Brakes', models.BooleanField(blank=True, default=False, null=True)),
                ('Batteries', models.BooleanField(blank=True, default=False, null=True)),
                ('other', models.TextField()),
                ('Address', models.CharField(max_length=80)),
                ('Firstname', models.CharField(max_length=80)),
                ('Lastname', models.CharField(max_length=80)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Fax', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
