# Generated by Django 4.1.5 on 2023-01-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
