# Generated by Django 4.1.5 on 2023-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rezervmodel_select_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervmodel',
            name='Add_a_mot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Batteries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Brakes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Cambelt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Clutches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Diagnose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Exhaust',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Full_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Interim_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Suspension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Tyres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='Wheelaligment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezervmodel',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
