# Generated by Django 4.1.5 on 2023-01-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_rezervmodel_add_a_mot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervmodel',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
