# Generated by Django 4.1.5 on 2023-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rezervmodel_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervmodel',
            name='make',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
