# Generated by Django 4.1.5 on 2023-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_rezervmodel_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervmodel',
            name='make',
            field=models.EmailField(blank=True, max_length=10, null=True),
        ),
    ]
