# Generated by Django 4.1.5 on 2023-01-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_rezervmodel_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervmodel',
            name='Fax',
        ),
        migrations.RemoveField(
            model_name='rezervmodel',
            name='select_title',
        ),
    ]
