# Generated by Django 4.1.5 on 2023-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_remove_rezervmodel_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervmodel',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
