# Generated by Django 4.1.5 on 2023-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_rezervmodel_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervmodel',
            name='Anything',
            field=models.TextField(blank=True, null=True),
        ),
    ]
